apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend-deployment
  labels:
    app: mern-backend
  namespace: mern-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend

    spec:
      containers:
        - name: mern-backend
          image: 17harsha08/mern-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: "PORT"
              value: "5000"
            - name: "MONGO_URL"
              value: "mongodb+srv://harsha:Harsha8080@cluster0.za0sveq.mongodb.net/learnMongo?retryWrites=true&w=majority&appName=Cluster0"
            - name: "JWT_SECRET_KEY"
              value: "cdsfifnbedfiubeduifgbndeoignsdoingviodbngibgioes!@#$%^&Ytvftgvghv"
            - name: "RAZORPAY_KEY_ID"
              value: "rzp_test_rkD0c6I1YhgGhp"
            - name: "RAZORPAYKEY_SECRET"
              value: "u73meOV3BaYu9hzJnTRaYOkj"